export const publicationTitles = [
  "📿 Terço dos Homens",
  "🌸 Terço das Mulheres",
  "👨‍👩‍👧‍👦 Encontro de Casais",
  "🕊 Grupo de Oração",
  "📖 Estudo Bíblico",
  "🙏 Adoração ao Santíssimo",
  "✝ Via-Sacra",
  "🎶 Ensaio do Coral",
  "🎼 Ministério de Música",
  "👶 Catequese Infantil",
  "🧑 Catequese Crisma",
  "💍 Curso de Noivos",
  "👴 Pastoral da Pessoa Idosa",
  "👶 Pastoral da Criança",
  "⛪ Santa Missa",
  "🌅 Missa da Manhã",
  "🌙 Missa da Noite",
  "🕊 Missa em Ação de Graças",
  "🖤 Missa de 7º Dia",
  "🎉 Missa Solene",
  "📿 Celebração da Palavra",
  "🙌 Missa Jovem",
  "📢 Aviso Importante",
  "⚠ Comunicado Oficial",
  "📝 Inscrições Abertas",
  "📌 Lembrete",
  "🔔 Mudança de Horário",
  "📅 Programação da Semana",
  "📍 Novo Evento"
];
